name: gingaf
description: multi-platform ginga player for web, mobile, and desktop
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  ncl_app:
    path: ncl_app
  ccws:
    path: ccws
  cupertino_icons: ^1.0.2
  webview_all: ^1.0.3
  logging: ^1.3.0
  video_player: ^2.8.6
  video_player_win: ^3.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  integration_test:
    sdk: flutter
  test: ^1.29.0

flutter:
  uses-material-design: true
  assets:
    - examples/

